# Use a slightly larger image for development tools/debugging
FROM python:3.12-slim AS base

WORKDIR /app

COPY backend/requirements.txt .

# Copy the rest of the application code
COPY backend/ ./backend/


# update pip
RUN pip install --no-cache-dir --upgrade pip

# Install dependencies
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --no-cache-dir -r requirements.txt

WORKDIR /app/backend

EXPOSE 8000

# Define entry point for local development usage
RUN python manage.py migrate
CMD ["python", "manage.py", "runserver"]
