# Generated by Django 6.0.4 on 2026-04-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('number', models.IntegerField(blank=True, max_length=20)),
                ('is_logged', models.BooleanField(default=False)),
            ],
        ),
    ]
