# Generated by Django 6.0.4 on 2026-04-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plan",
            field=models.CharField(
                choices=[("free", "Free"), ("plus", "Plus"), ("pro", "Pro")],
                default="free",
                max_length=10,
            ),
        ),
    ]
