# Generated by Django 6.0.4 on 2026-05-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_preference',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email y SMS'), ('in_app', 'Solo en la app')], default='in_app', max_length=10),
        ),
    ]
