# Generated by Django 6.0.4 on 2026-04-30 05:37

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.products.models.product_image_path
            ),
        ),
    ]
