# Generated by Django 6.0.4 on 2026-04-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[
                    ("CUP", "Peso Cubano (CUP)"),
                    ("MLC", "Peso Convertible (MLC)"),
                    ("USD", "Dólar Estadounidense (USD)"),
                    ("EUR", "Euro (EUR)"),
                ],
                default="CUP",
                max_length=3,
            ),
        ),
    ]
